## IMPORT THE RELEVANT LIBRARY

In [1]:
import pandas as pd
import numpy as np

Load the data

In [2]:
data_preprocessed = pd.read_csv('Absenteeism_preprocessed.csv')

In [3]:
data_preprocessed.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0         0         0         0         1            7                1   
1         0         0         0         0            7                1   
2         0         0         0         1            7                2   
3         1         0         0         0            7                3   
4         0         0         0         1            7                3   

   Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                     289                36   33                  239.554   
1                     118                13   50                  239.554   
2                     179                51   38                  239.554   
3                     279                 5   39                  239.554   
4                     289                36   33                  239.554   

   Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0               30          0         2    1                          4  
1               31          0         1    0                          0  
2               31          0         0    0                          2  
3               24          0         2    0                          4  
4               30          0         2    1                          2

## creating targets(median)

In [4]:
data_preprocessed['Absenteeism Time in Hours'].median()

3.0

In [5]:
targets = np.where(data_preprocessed['Absenteeism Time in Hours'] > 
                  data_preprocessed['Absenteeism Time in Hours'].median(), 1 , 0)

In [6]:
targets

array([1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,

In [7]:
data_preprocessed['Excessive Absentiasm'] = targets

In [8]:
data_preprocessed

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  \
0                 30          0         2    1                          4   
1                 31          0         1    0                          0   
2                 31          0         0    0                          2   
3                 24          0         2    0                          4   
4                 30          0         2    1                          2   
..               ...        ...       ...  ...                        ...   
695               22          1         2    0                          8   
696               24          0         1    2                          3   
697               25          1         0    0                          8   
698               25          1         0    0                          2   
699               25          0         1    1                          2   

     Excessive Absentiasm  
0                       1  
1                       0  
2                       0  
3                       1  
4                       0  
..                    ...  
695                     1  
696                     0  
697                     1  
698                     0  
699                     0  

[700 rows x 16 columns]

## A comment on targets

In [9]:
targets.sum() / targets.shape[0]

0.45571428571428574

In [10]:
data_with_targets = data_preprocessed.drop(['Absenteeism Time in Hours', 'Day of the Week', 'Daily Work Load Average'], axis = 1)

In [11]:
data_with_targets is data_preprocessed

False

In [12]:
data_with_targets.head()

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0         0         0         0         1            7   
1         0         0         0         0            7   
2         0         0         0         1            7   
3         1         0         0         0            7   
4         0         0         0         1            7   

   Transportation Expense  Distance to Work  Age  Body Mass Index  Education  \
0                     289                36   33               30          0   
1                     118                13   50               31          0   
2                     179                51   38               31          0   
3                     279                 5   39               24          0   
4                     289                36   33               30          0   

   Children  Pet  Excessive Absentiasm  
0         2    1                     1  
1         1    0                     0  
2         0    0                     0  
3         2    0                     1  
4         2    1                     0

## Select the inputs for the regression

In [13]:
data_with_targets.shape

(700, 13)

In [14]:
data_with_targets.iloc[:, 0:14]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Distance to Work  Age  Body Mass Index  \
0                       289                36   33               30   
1                       118                13   50               31   
2                       179                51   38               31   
3                       279                 5   39               24   
4                       289                36   33               30   
..                      ...               ...  ...              ...   
695                     179                22   40               22   
696                     225                26   28               24   
697                     330                16   28               25   
698                     235                16   32               25   
699                     291                31   40               25   

     Education  Children  Pet  Excessive Absentiasm  
0            0         2    1                     1  
1            0         1    0                     0  
2            0         0    0                     0  
3            0         2    0                     1  
4            0         2    1                     0  
..         ...       ...  ...                   ...  
695          1         2    0                     1  
696          0         1    2                     0  
697          1         0    0                     1  
698          1         0    0                     0  
699          0         1    1                     0  

[700 rows x 13 columns]

In [15]:
data_with_targets.iloc[:, : -1]

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  \
0           0         0         0         1            7   
1           0         0         0         0            7   
2           0         0         0         1            7   
3           1         0         0         0            7   
4           0         0         0         1            7   
..        ...       ...       ...       ...          ...   
695         1         0         0         0            5   
696         1         0         0         0            5   
697         1         0         0         0            5   
698         0         0         0         1            5   
699         0         0         0         1            5   

     Transportation Expense  Distance to Work  Age  Body Mass Index  \
0                       289                36   33               30   
1                       118                13   50               31   
2                       179                51   38               31   
3                       279                 5   39               24   
4                       289                36   33               30   
..                      ...               ...  ...              ...   
695                     179                22   40               22   
696                     225                26   28               24   
697                     330                16   28               25   
698                     235                16   32               25   
699                     291                31   40               25   

     Education  Children  Pet  
0            0         2    1  
1            0         1    0  
2            0         0    0  
3            0         2    0  
4            0         2    1  
..         ...       ...  ...  
695          1         2    0  
696          0         1    2  
697          1         0    0  
698          1         0    0  
699          0         1    1  

[700 rows x 12 columns]

In [16]:
unscaled_inputs = data_with_targets.iloc[:, : -1]

## Standardize the data

In [17]:
from sklearn.preprocessing import StandardScaler
assenteeism_scaler = StandardScaler()

In [18]:
assenteeism_scaler.fit(unscaled_inputs)

StandardScaler()

In [19]:
scaled_inputs = assenteeism_scaler.transform(unscaled_inputs)

In [20]:
scaled_inputs

array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         0.88046927,  0.26848661],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.91902997, -0.58968976],
       ...,
       [ 1.73205081, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ...,  2.23224237,
        -0.91902997, -0.58968976],
       [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
        -0.01928035,  0.26848661]])

In [21]:
scaled_inputs.shape

(700, 12)

## Split the data into train and test and shuffle

### Import the relevant module

In [22]:
from sklearn.model_selection import train_test_split

### Split

In [23]:
train_test_split(scaled_inputs, targets)
## array 1: a trainning dataset with inputs
## array 2: a trainning dataset with targets
## array 3: a test dataset with inputs
## array 4: a test dataset with targets

[array([[-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        ...,
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.91902997, -0.58968976],
        [ 1.73205081, -0.09298136, -0.31448545, ..., -0.44798003,
         -0.01928035,  1.12666297],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661]]),
 array([[-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          0.88046927,  0.26848661],
        [-0.57735027, -0.09298136,  3.17979734, ..., -0.44798003,
         -0.01928035,  3.70119207],
        [-0.57735027, -0.09298136, -0.31448545, ..., -0.44798003,
          2.67996851, -0.58968976],
        ...,
        [-0.57735027, -0.09298136,  3.17979734, ..., -

In [24]:
x_train, x_test, y_train, y_test = train_test_split(scaled_inputs, targets, train_size = 0.8, random_state = 20)

In [25]:
print(x_train.shape, y_train.shape)

(560, 12) (560,)


In [26]:
print(x_test.shape, y_test.shape)

(140, 12) (140,)


## Logistic regression with sklearn

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

### Training the model

In [28]:
reg = LogisticRegression()

In [29]:
reg.fit(x_train, y_train)

LogisticRegression()

In [30]:
reg.score(x_train, y_train)

0.7928571428571428

## Manually check accuracy

In [31]:
model_outputs = reg.predict(x_train)

In [32]:
model_outputs

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0,

In [33]:
y_train

array([0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1,
       1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,

In [34]:
model_outputs == y_train

array([ True,  True, False,  True,  True,  True,  True,  True,  True,
        True, False,  True, False, False,  True,  True,  True,  True,
       False,  True, False,  True, False, False,  True,  True,  True,
       False,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True, False,  True,  True,
        True,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True, False,  True,  True, False, False, False,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,

In [35]:
np.sum(model_outputs == y_train)

444

In [36]:
model_outputs.shape[0]

560

In [37]:
np.sum(model_outputs == y_train) / model_outputs.shape[0]

0.7928571428571428

# Finding the intercept and coefficients

In [38]:
reg.intercept_

array([-0.21592511])

In [39]:
reg.coef_

array([[ 2.06169698,  0.33277691,  1.55845314,  1.30952219,  0.01763815,
         0.72844847, -0.06036379, -0.21323765,  0.33862454, -0.15591976,
         0.37754867, -0.31929018]])

In [40]:
unscaled_inputs.columns.values

array(['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Transportation Expense', 'Distance to Work', 'Age',
       'Body Mass Index', 'Education', 'Children', 'Pet'], dtype=object)

In [41]:
feature_name = unscaled_inputs.columns.values

In [42]:
summary_table = pd.DataFrame (columns = ['Feature name'], data = feature_name)

summary_table['Coefficient'] = np.transpose(reg.coef_)

summary_table

Feature name  Coefficient
0                 Reason_1     2.061697
1                 Reason_2     0.332777
2                 Reason_3     1.558453
3                 Reason_4     1.309522
4              Month Value     0.017638
5   Transportation Expense     0.728448
6         Distance to Work    -0.060364
7                      Age    -0.213238
8          Body Mass Index     0.338625
9                Education    -0.155920
10                Children     0.377549
11                     Pet    -0.319290

In [43]:
summary_table.index = summary_table.index + 1 
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

Feature name  Coefficient
0                Intercept    -0.215925
1                 Reason_1     2.061697
2                 Reason_2     0.332777
3                 Reason_3     1.558453
4                 Reason_4     1.309522
5              Month Value     0.017638
6   Transportation Expense     0.728448
7         Distance to Work    -0.060364
8                      Age    -0.213238
9          Body Mass Index     0.338625
10               Education    -0.155920
11                Children     0.377549
12                     Pet    -0.319290

## Interpreting the coefficients

In [44]:
summary_table['Odds_ratio'] = np.exp(summary_table.Coefficient)

In [45]:
summary_table

Feature name  Coefficient  Odds_ratio
0                Intercept    -0.215925    0.805796
1                 Reason_1     2.061697    7.859296
2                 Reason_2     0.332777    1.394836
3                 Reason_3     1.558453    4.751466
4                 Reason_4     1.309522    3.704403
5              Month Value     0.017638    1.017795
6   Transportation Expense     0.728448    2.071864
7         Distance to Work    -0.060364    0.941422
8                      Age    -0.213238    0.807964
9          Body Mass Index     0.338625    1.403016
10               Education    -0.155920    0.855628
11                Children     0.377549    1.458704
12                     Pet    -0.319290    0.726665

In [46]:
summary_table.sort_values('Odds_ratio', ascending = False)

Feature name  Coefficient  Odds_ratio
1                 Reason_1     2.061697    7.859296
3                 Reason_3     1.558453    4.751466
4                 Reason_4     1.309522    3.704403
6   Transportation Expense     0.728448    2.071864
11                Children     0.377549    1.458704
9          Body Mass Index     0.338625    1.403016
2                 Reason_2     0.332777    1.394836
5              Month Value     0.017638    1.017795
7         Distance to Work    -0.060364    0.941422
10               Education    -0.155920    0.855628
8                      Age    -0.213238    0.807964
0                Intercept    -0.215925    0.805796
12                     Pet    -0.319290    0.726665

# Testing the model

In [47]:
reg.score(x_test, y_test)

0.7357142857142858

In [48]:
predicted_proba = reg.predict_proba(x_test)
predicted_proba

array([[0.76856576, 0.23143424],
       [0.59189061, 0.40810939],
       [0.43116505, 0.56883495],
       [0.77507579, 0.22492421],
       [0.07186867, 0.92813133],
       [0.29855922, 0.70144078],
       [0.28992297, 0.71007703],
       [0.06962859, 0.93037141],
       [0.73879405, 0.26120595],
       [0.77137179, 0.22862821],
       [0.48732418, 0.51267582],
       [0.14154312, 0.85845688],
       [0.0381666 , 0.9618334 ],
       [0.71837807, 0.28162193],
       [0.22126725, 0.77873275],
       [0.49364913, 0.50635087],
       [0.48600488, 0.51399512],
       [0.492603  , 0.507397  ],
       [0.35911971, 0.64088029],
       [0.03391116, 0.96608884],
       [0.73469709, 0.26530291],
       [0.77507579, 0.22492421],
       [0.4584618 , 0.5415382 ],
       [0.45322205, 0.54677795],
       [0.15184499, 0.84815501],
       [0.73981188, 0.26018812],
       [0.46024947, 0.53975053],
       [0.90157198, 0.09842802],
       [0.17369215, 0.82630785],
       [0.77507579, 0.22492421],
       [0.

In [49]:
predicted_proba[:1]

array([[0.76856576, 0.23143424]])

## Save the model

In [50]:
import pickle

In [51]:
with open('model', 'wb') as file:
    pickle.dump(reg, file)